### ISSUE TITLE
browser-client has index.html on the wrong place?

### ISSUE THREAD

**Issue by montoyamoraga** [lisajamhoury/Electron-to-Browser-Simple-Peer-Example#1]
hi @lisajamhoury 
i tried running the browser from browser_client/ and it didn't work.
the index.html file is on browser_client/dist
should that remain there? i didn't understand why there is both a dist/ and src/ file there
:)

**Comment by lisajamhoury** [comment]
Hi! Yes, you need to go into the dist folder in your browser. I've added this to the instructions in the readme with [this commit](https://github.com/lisajamhoury/Electron-to-Browser-Simple-Peer-Example/commit/735a3f1d5d55f052d6803e5987b23519fd8e1349).

The dist file is needed because the client requires two npm modules — see [lines 1 and 2](https://github.com/lisajamhoury/Electron-to-Browser-Simple-Peer-Example/blob/httpslocalhost/browser_client/src/webrtc_peer_client.js#L1) of the src file.   

You cannot use "require" in the browser, so I'm using Browserify to bundle the dependencies in the client code, the result of which is in dist. [Learn more about Browserify](http://browserify.org/).
